### ISSUE TITLE
Multiple comments on approval/disapproval

### ISSUE THREAD

**Issue by EarthlingRich** [exercism/csharp-analyzer#38]
Currently the analysers always approve or disapprove submission with one comment. I would like to start a discussion if it would be better to give multiple comments. This prevents users needing to make multiple submissions to get all the available feedback. This could tire or annoy users. It also gives more feedback to users that do not make a new submission for a approved exercise, but take the lessons learned to a new exercise.

I think it is important to not overload users with to many comments at one time, so maybe we should set a maximum amount or have different levels of comments and only return for the most severe level we detect comments for.

Would love to hear ideas about this.

Extra info:
It has been decided that this is a good idea. Current progress.
- [x] Two-fer
- [x] Leap
- [x] Gigasecond

**Comment by ErikSchierboom** [comment]
I'd be happy to discuss this, although I would slightly prefer to do this in the general #project-auto-mentor channel in the slack community, as this is really something that is a cross-track concern. Would that be fine with you?

**Comment by EarthlingRich** [comment]
Sorry for the late response. I saw the comments on Slack about multiple comments.

- Multiple comments would be better.
- Split comments for reject and approve.
- 1 to 3 comments is best, but more is technically allowed.
- Order the comments by importance, because the frontend will not show more then 3 comments.

Is it okay if I do a PR about this for two-fer?

**Comment by ErikSchierboom** [comment]
The [two-fer PR](#39) has been merged. The next step is to apply this to the `leap` and `gigasecond` analyzers.

**Comment by EarthlingRich** [comment]
Nice! I will take a look this week.

**Comment by ErikSchierboom** [comment]
Great. If you don't feel like doing it, just let me know! It is by no means your responsibility to also update the others (although you'd be most welcome to it of course).

**Comment by EarthlingRich** [comment]
This is now implemented. 🎉
